include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_print: ignore
    avoid_setters_without_getters: ignore
    comment_references: ignore
    document_ignores: ignore
    eol_at_end_of_file: ignore
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    prefer_asserts_in_initializer_lists: ignore
    prefer_asserts_with_message: ignore
    public_member_api_docs: ignore
    require_trailing_commas: ignore
    type_annotate_public_apis: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
  exclude:
    - build/**
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    file_names: false
    type_annotate_public_apis: false
    require_trailing_commas: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false